version: '3'
services:
  mysql:
    build:
      context: './mysql'
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  nodeapp:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
